server:
  port: 9020

spring:
  application:
    name: webflux-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://www.server.com:8000/.well-known/jwks.json

logging:
  level:
    org.springframework.security: debug